#This code will take as input the list of karyotypes generated by the Complete Analysis.R script 
#and will plot a network representing the relationship between those karyotypes.
#_______________________________________________________________________________________________

#inputs
karyo_input <- BPK081_karyotypes
sample_name <- "BPK081"

#_________________________________________________________________________________________________

#parameters
number_of_clusters <-0 #if 0, will not cluster the nodes.
cluster_method <- "ward.D2" #which method will be used for hyerarchical clustering of karyotypes.#Only used if number of groups is higher than 1
mass_factor <- 0.5 #play along with this value to change how nodes distantiate from one another (values between 0.5 and 1 are recommended)
mass_exp_factor <- 1
remove_polyploid <- TRUE #if TRUE, will plot in the network only diploid karyotypes. 
#_________________________________________________________________________________________________
#functions
#this function will calculate the number of chromosomes with different somies between each pair of karyotype
#and return a square matrix with the pairwise distances between all karyotypes. 

karyo_dist_matrix <- function(x, splitter = "_", verbose = FALSE){
  x <- strsplit(x, split = splitter)
  
  print(paste(length(x), "identified karyotypes"))
  
  diff_matrix <- matrix(nrow = length(x))
  
  for(i in c(1:length(x))){
    karyo_1 <- x[i]
    karyo_1 <- unlist(karyo_1)
    karyo_1 <- as.numeric(unlist(karyo_1))
    karyo_1_size <- length(karyo_1)
    vec <- c()
    for(j in c(1:length(x))){
      karyo_2 <- x[j]
      karyo_2 <- unlist(karyo_2)
      karyo_2 <- as.numeric(unlist(karyo_2))
      karyo_2_size <- length(karyo_2)
      vec <- c(vec, length(which(karyo_1 != karyo_2)))
      
      if(karyo_1_size != karyo_2_size){
        stop(paste("Karyo", i, "and", j, "have a different number of chromosomes"))
      }
      if(verbose == TRUE){
        print(paste("comparing karyotype", i, "with", j))
      }
    }
    #print(vec)
    diff_matrix <- cbind(diff_matrix, vec)
  }
  
  diff_matrix <- diff_matrix[,-1]
  diff_matrix <- numeric.matrix(data.frame(diff_matrix))
  colnames(diff_matrix) <- c(1:ncol(diff_matrix))
  return(diff_matrix)
}

#this function will create the HTML formated text to be displayed as the tooltip of the nodes. 
create_nodes_labels <- function(nodes){
  labels <- character(nrow(nodes))
  karyotypes <- as.character(nodes$karyotype)
  
  colors <- c("#001221","#002342", "#014175","#00c3ff", "#33ff00", "#fffa00", "#ffa600", "#D73027", "#A50026", "#541b1b", "#4d0600", rep("#300501", times = 100))
  #colors <- c("#001221", "#4575B4", "#a4cbe0", "#E0F3F8", "#FFFFBF", "#FDAE61", "#F46D43", "#D73027", "#A50026", "#541b1b", rep("#300501", times = 100))
  
  for(i in c(1:nrow(nodes))){
    karyotype <- unlist(strsplit(karyotypes[i], split = "_"))
    karyo_id <- paste("<b>Kar", nodes$id[i], "</b><br>", sep = "")
    number_of_cells <- paste(nodes$number_of_cells[i],
                             ifelse(nodes$number_of_cells[i] >2, "cells", "cell"),
                             "<br><br><b>Somies:</b><br>")
    karyo_colors <- colors[as.numeric(karyotype)+1]
    chromos <- c(1:length(karyotype))
    chromos[which(as.numeric(chromos) < 10)] <- paste("0", chromos[which(as.numeric(chromos) < 10)], sep = "")
    chromos <-  paste("chr", chromos, ":", sep = "")
    karyotype <- paste("<b><span style=\"color:", karyo_colors, "\">", karyotype, "</span></b>", sep = "") #adding color to each somy value
    karyotype <- paste(chromos, " <b>",karyotype,"</b>", sep = "")
    karyotype <- paste(karyotype, "<br>", sep = "")#adding a line break at the end of each somy value
    karyotype <- paste(karyotype, collapse = "")
    label <- paste(karyo_id, number_of_cells, karyotype,  collapse = "")
    labels[i] <- label
  }
  return(labels)
}


#this function will create the HTML formated text to be displayed as the tooltip of the edges.
create_edge_labels <- function(edges){
  from <- edges$kar_from
  to <- edges$kar_to
  
  #comparing each pair ok karyotypes
  labels <- character(length(from))
  for(i in c(1:length(from))){
    #converting to vectors
    kar1_id <- edges$from[i]
    kar2_id <- edges$to[i]
    kar1 <- unlist(strsplit(as.character(from[i]), split = "_"))
    kar2 <-unlist(strsplit(as.character(to[i]), split = "_"))
    
    #getting which are the different chromosomes
    diff_chromo <- which(kar1 != kar2)
    somy_change <- as.numeric(kar1[diff_chromo]) - as.numeric(kar2[diff_chromo])
    #marking in red the chromosome that changed between both karyotypes (using html code)
    kar1[diff_chromo] <- paste("<b><span style=\"color:red\">", kar1[diff_chromo], "</span></b>", sep = "")
    kar2[diff_chromo] <- paste("<b><span style=\"color:red\">", kar2[diff_chromo], "</span></b>", sep = "")
    #adding a space between somies of kar 1 and kar 2
    label <- paste(kar1, kar2, sep = " -> ")
    #making a vector with chromosomes names
    chromos <- c(1:length(kar1))
    chromos[which(as.numeric(chromos) < 10)] <- paste("0", chromos[which(as.numeric(chromos) < 10)], sep = "")
    chromos <-  paste("chr", chromos, ":", sep = "")
    #adding chromosomes names to the label
    label <- paste(chromos, label)
    karyos <- paste("<b>kar", kar1_id, " -> kar" , kar2_id, "</b>", sep = "")
    label <- c(karyos, label)
    #adding a html line brek between each chromosome
    label <- paste(label, "<br>", sep = "")
    label <- paste(label, collapse = "")
    #making karyotypes names
    
    labels[i] <- label
  }
  return(labels)
} 

#___________________________________________________________________________
#code
library(dplyr)
library(pegas)
library(visNetwork)
library(ggplot2)
library(cowplot)

try(rm(network_rmst), silent = TRUE)
try(rm(network_dist_matrix), silent = TRUE)
try(rm(network_karyotypes), silent = TRUE)
try(rm(edges), silent = TRUE)
try(rm(nodes), silent = TRUE)


vis_solver <- c("barnesHut", "repulsion", "hierarchicalRepulsion", "forceAtlas2Based")

network <- karyo_input
network_karyotypes <- network
network <- network$karyotype
network <- as.character(unlist(network))

network_dist_matrix <- karyo_dist_matrix(network)

if(remove_polyploid){
  network_karyotypes <- filter(network_karyotypes, baseline_ploidy == 2)
  filter <- which(colnames(network_dist_matrix) %in% as.character(network_karyotypes$position))
  network_dist_matrix <- network_dist_matrix[filter, filter]
  colnames(network_dist_matrix) <- filter
  rownames(network_dist_matrix) <- filter
}


network_rmst <- rmst(network_dist_matrix, B = 10)
nodes <- data.frame(id = network_karyotypes$position, label = network_karyotypes$position, number_of_cells = network_karyotypes$number_of_cells, karyotype = network_karyotypes$karyotype)

nodes <- nodes %>%
mutate(label = ifelse(label < 10, paste("  ", label, "  ", sep = ""), ifelse(label < 100, paste(" ", label, " ", sep = ""), label))) %>%
mutate(size = (sqrt(as.numeric(number_of_cells)*3.14) * 2))%>% # here will calculate the area of each node as a function of the number of cells
mutate(size = size * 1.5) %>%
mutate(mass = (size/min(size))) %>%
mutate(mass = mass * mass_factor) %>%
mutate(mass = mass^mass_exp_factor) %>%
mutate(mass = ifelse(mass < 0.8 , 0.8 , mass))%>%
mutate(font.size = ifelse(id < 10, size*0.9, size)+20)


clusters <- NULL
if(number_of_clusters > 0){
  clusters <- network_dist_matrix
  #clusters <- cor(clusters)
  #diag(clusters) <- 0
  clusters <- as.dist(clusters)
  clusters <- hclust(clusters, method = cluster_method)
  clusters <- cutree(clusters, k = number_of_clusters)
  nodes <- nodes %>%
    #mutate(color.background = clusters) %>%
    mutate(group = clusters)%>%
    mutate(shape = ifelse(number_of_cells == 1, "dot",  "circle"))%>%
    mutate(label = ifelse(shape == "dot", NA, label)) %>%
    mutate(size = ifelse(shape == "dot", size*2, size))
  }else{
  nodes <- nodes %>%
    mutate(shape = ifelse(number_of_cells == 1, "dot",  "circle")) %>%
    mutate(color.background = ifelse(number_of_cells == 1, "#3cb314", "#454545")) %>%
    mutate(borderWidth = ifelse(shape == "dot", 0, NA)) %>%
    mutate(label = ifelse(shape == "dot", NA, label)) %>%
    mutate(size = ifelse(shape == "dot", size*2, size)) %>%
    mutate(font.color = ifelse(shape == "dot", NA, "white")) #%>%
    #mutate(mass = ifelse(number_of_cells <= 2, 1.6 * mass, mass))
}

nodes$title <- create_nodes_labels(nodes)

edges <- data.frame(from = network_rmst[,1], to = network_rmst[,2], steps = network_rmst[,3], alt_link = FALSE)

edges <- rbind(edges, data.frame(from = attr(network_rmst, "alter.links")[,1], to = attr(network_rmst, "alter.links")[,2], steps = attr(network_rmst, "alter.links")[,3], alt_link = TRUE))

edges$from <- nodes$id[edges$from]
edges$to <- nodes$id[edges$to]

edges <- edges %>%
mutate(dashes = alt_link) %>%
mutate(label = ifelse(steps == 1, NA, as.character(steps))) %>%
#mutate(value = 1/steps/5) %>%
mutate(length = ifelse(steps == 1, steps *10, steps * 100)) %>%
mutate(physics = !alt_link) %>%
mutate(color = ifelse(steps == 1, "black", "#ff8800")) %>%
mutate(color = ifelse(alt_link == TRUE, "#737272", color)) %>%
mutate(width = ifelse(color == "black", 8, ifelse(color == "#ff8800", 3, 2))) %>%
mutate(smooth = physics)


edges <- filter(edges, alt_link == FALSE | alt_link == TRUE & steps == 1)
#edges <- filter(edges, alt_link == FALSE)

#adding karyotype information to edge list (needed to make the tooltip)

kar_from <- c()
kar_to <- c()
for(i in c(1:nrow(edges))){ #will loop through each pair of karyotypes in the edgelist
  kar <- nodes$karyotype[which(nodes$id == edges$from[i])]
  kar <- as.character(kar)
  kar_from <- c(kar_from, kar)
  kar <- nodes$karyotype[which(nodes$id == edges$to[i])]
  kar <- as.character(kar)
  kar_to <- c(kar_to, kar)
}

edges$kar_from <- kar_from
edges$kar_to <- kar_to

edges$title <- create_edge_labels(edges)
edges <- mutate(edges, title = ifelse(alt_link, NA, title))

ledges <- data.frame(color = c("black", "#ffa6af"), label = c("Change in 1 chromosome", "Change in 2 or more chromosomes"), shape = c("box", "box"))

visNetwork(nodes, edges, main = sample_name, height = "95vh", width = "100%")%>%
#visNetwork(nodes, edges, main = sample_name) %>%
#visIgraphLayout(physics = FALSE) %>%
visIgraphLayout(physics = TRUE, layout = "layout_with_dh") %>%
visPhysics(solver = vis_solver[1], forceAtlas2Based = FALSE, stabilization = FALSE) %>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;line-height:1; white-space: nowrap;
font-size:10px;background-color: #f2edbd;') %>%
#visLayout(hierarchical = FALSE) %>%
visOptions(highlightNearest = list(enabled = T, degree = 0, hover = F), selectedBy = "group", nodesIdSelection = TRUE , collapse = FALSE) %>%
visNodes(color = list(border = "black"), font = list(face = "consolas"), shadow = TRUE, shape = "circle", scaling = list(label = list(drawThreshold = 1))) %>%
visEdges(font = list(size = 50), scaling = list(label = list(drawThreshold = 1))) %>%
#visLegend(addNodes = ledges)%>%
visExport() %>% 
visSave(paste(getwd(),"/",sample_name, "_Network.html", sep = ""))

print(paste("Network for", sample_name, "built."))



